Project Implementation
MarcoDDM/recipe-app pull request #22
Opened 2023-09-16 21:14 UTC by MarcoDDM

**Description**

Our team of two has been diligently working on implementing the project requirements, and we would greatly appreciate your feedback on our progress. Your insights are highly valuable to us.

**Here's a summary of what we've achieved:**

**Project Requirements Implemented:**
- Successfully adhered to the wireframes layout.
- Personalized the design including colors, typography, spacings, etc.
- Developed the Login and Registration pages using Devise.
- Created the Food List, Recipes List, Public Recipe List, Recipe Details, and General Shopping List views as specified.
- Ensured the correct functionality for adding, deleting, and toggling the privacy of recipes.
- Designed a user-friendly navigation menu for seamless access to all pages.
- Committed to code quality by writing unit and integration tests.

**Additional Requirements (if applicable):**
- Implemented the Inventories List, Inventory Details, and Inventory Shopping List views.
- Ensured the proper functionality for adding, deleting, and selecting inventories for shopping lists.

Our repository on GitHub is structured following the Gitflow model, and Devise handles authentication. We've also integrated RSpec and Capybara for comprehensive testing.

As a team of two, we've fairly distributed tasks and have been collaborating effectively. Each task has been time-estimated and organized on our Kanban board.

We kindly request your review of our progress, and any feedback, suggestions, or improvements you can offer would be highly appreciated. Your guidance is instrumental to our success.

Thank you for dedicating your time and expertise to support our project. We look forward to hearing from you.
I add a screenshot of tests to the reviewer convenience:
![rspec_capstone](https://github.com/MarcoDDM/recipe-app/assets/43345162/11a23e5c-f2c4-44f0-89c9-a3983363594e)

2023-09-16 21:27 UTC, Reem-lab commented
Hello @MarcoDDM could you check your slack?

2023-09-16 22:49 UTC, Reem-lab requested changes
# Hi Team, 👋🏻👋🏻

Great job so far! 💯🤩🚀
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media4.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>


## Highlights

- No Linters error ✨
- Followed Gitflow 🔥
- Great working on the functionality 💯
- Great set up the models and schema 🤩🤩
- Professional README 💯
- Kudos for adding the validation in the models ✨
- Great for writing unit tests, all passed ✅
- Great job on writing the views ✨✨


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-16 22:49 UTC, Reem-lab commented on app/views/foods/index.html.erb
> +          <td><%= food.quantity %></td>
- [ ] Great job working on the project overall but I think you have some changes to work on so here on the food list page I think it would be great if you style the page the same as the given wireframe so Kindly work on it to be the same 💯🔥⭐kindly style the table to be the same as well  with the button ♻

- Your page 
![image](https://github.com/MarcoDDM/recipe-app/assets/58553711/2ac6eb36-ea0e-4564-b1b1-b71d660fc107)

- Given
![image](https://github.com/MarcoDDM/recipe-app/assets/58553711/0d6fcf5c-70bb-4b2c-a554-77b505a23066)

2023-09-16 22:49 UTC, Reem-lab commented on app/views/recipes/index.html.erb
> +
- [ ] I think it would be great here if you positioned the button under the title of the recipe since it is like this in the given wireframe so kindly fix it ♻⭐🚀🤩

- Yours
![image](https://github.com/MarcoDDM/recipe-app/assets/58553711/f9f6011e-73f0-4671-81cd-2c34b2ff7130)


- Given 
![image](https://github.com/MarcoDDM/recipe-app/assets/58553711/86ec832c-991a-4019-bc2b-9f38b800b540)

2023-09-16 22:49 UTC, Reem-lab commented on app/views/recipes/show.html.erb
> +                            <%= link_to "Edit", edit_recipe_recipe_food_path(food) %>
- [ ] I think it would be great if you worked on the styles for the recipe details to make it match the given wireframe so I highly recommend adding more style to make it the same 🤩🚀⭐♻

- I think here you can make the information and public button beside each other with space between them ♻⭐
- Then you can make the same for the two buttons ✨
- Then you can style your table to match the given table ⭐

- Your
![image](https://github.com/MarcoDDM/recipe-app/assets/58553711/19aa9702-e23a-4b54-87c1-f44448e82033)

- Given
![image](https://github.com/MarcoDDM/recipe-app/assets/58553711/e5180761-5a2f-498d-9f9c-8442e05fbbc3)

2023-09-16 22:49 UTC, Reem-lab commented on app/views/recipes/show.html.erb
> +             <p> <%= @recipe.description %>
- [ ] Great job working so far but I think there is a bug since whenever I try to open the public recipes this error pops up so kindly check this error and try to solve it to make sure that everything is working properly ⭐✨♻

- Even after adding a recipe with a public status

![image](https://github.com/MarcoDDM/recipe-app/assets/58553711/03527d23-ffe5-4a3b-8d2d-7f94b9b8056a)

2023-09-16 22:49 UTC, Reem-lab commented on app/views/recipe_foods/new.html.erb
> +
- [ ] When I try to open add ingredient it opens for me this form but I think this is not creating a recipe this is for adding the ingredients for this recipe so if the user makes a recipe with food is not found on your food list so this should be shown in the tables the food and the quantity and the value with two actions buttons [modify and delete ] so kindly add them♻✨⭐


- [ ] So here I think it would be great if you make the food input not a number but a text ✨♻


- After pressing the button to add them I can't see them in the tale so kindly fix this functionality as well ✅😄


![image](https://github.com/MarcoDDM/recipe-app/assets/58553711/b5883c58-35e8-42ab-b0da-7b7c9a5ac3e1)

- Wireframe

![image](https://github.com/MarcoDDM/recipe-app/assets/58553711/5f0a200b-a425-43ca-a50f-e480141c8839)

2023-09-16 22:49 UTC, Reem-lab commented on app/views/users/general_food_list.html.erb
> +<table>
- [ ] When I try to press on the general shopping list I can't be able to see the page open so kindly fix the routes here to link to the required page 😄💯

- I think the shopping list could be counted if you have missing food in the recipe and not found in the food list so it should be in the shopping list 🔥😄🙏🏻


https://github.com/MarcoDDM/recipe-app/assets/58553711/efd07572-7be1-4bec-8125-e4f22ea50ae2

2023-09-16 22:49 UTC, Reem-lab commented on app/controllers/recipes_controller.rb
> +  end
- [ ] I think it would be great if you made this method a private method to make these parameters strong parameters so here it shows the importance of the access control🙏🏻😄🔥💯you can check this [lesson](https://www.geeksforgeeks.org/ruby-access-control/?ref=lbp) to understand more about it

2023-09-17 03:24 UTC, MarcoDDM commented
### **REMEMBER**
You should change all your credentials on database.yml to run the app.

[Watch the video showing the app working properly](https://www.loom.com/share/a185b2cd5f1549c8a3c4df735a70edac?sid=d80d9b9d-d212-4b58-a913-4d924609ec55)

2023-09-17 03:27 UTC, MarcoDDM commented on app/views/recipes/show.html.erb
> +             <p> <%= @recipe.description %>
[Watch the video showing the app working properly](https://www.loom.com/share/a185b2cd5f1549c8a3c4df735a70edac?sid=d80d9b9d-d212-4b58-a913-4d924609ec55)

2023-09-17 04:28 UTC, merged